apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: auth-o-tron
build:
  local:
    useBuildkit: true
    concurrency: 1

  tagPolicy:
    customTemplate:
      # Use the CARGO_VERSION and TARGETARCH environment variables to tag the image
      # We will build multi-arch images, so we need to tag them with the target architecture
      template: "{{.CARGO_VERSION}}-{{.TARGETARCH}}"
      components:
        - name: CARGO_VERSION
          envTemplate:
            template: '{{.CARGO_VERSION}}'
        - name: TARGETARCH
          envTemplate:
            template: '{{.TARGETARCH}}'

  artifacts:
    - image: "auth-o-tron"
      context: .
      docker:
        dockerfile: Dockerfile
        target: release

    - image: "auth-o-tron-debug"
      context: .
      docker:
        dockerfile: Dockerfile
        target: debug
