apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: auth-o-tron
build:
  local:
    useBuildkit: true
    concurrency: 1

  tagPolicy:
    customTemplate:
      # Use only the CARGO_VERSION as tag
      # Extracted from Cargo.toml in the CI workflow
      # For local builds, you can set CARGO_VERSION manually
      template: "{{.CARGO_VERSION}}"
      components:
        - name: CARGO_VERSION
          envTemplate:
            template: '{{.CARGO_VERSION}}'

  artifacts:
    - image: "auth-o-tron"
      context: .
      docker:
        dockerfile: Dockerfile
        target: release

    - image: "auth-o-tron-debug"
      context: .
      docker:
        dockerfile: Dockerfile
        target: debug