version: 2.0.0

logging:
  level: "debug"
  format: "console"

auth:
  timeout_in_ms: 3000 # 3 seconds

providers:
  - name: "plain-provider"
    type: "plain"
    realm: "localrealm"
    users:
      - username: "test_user"
        # Hash of secret123 for this example only.
        password_hash: "$argon2id$v=19$m=19456,t=2,p=1$YXV0aG90cm9uLWRvYy0wMA$nIbsJAh7Dy4U3lp30gdyZp5xIvGEixDw6egf5H1ckpQ"
      - username: "test_user2"
        # Hash of p@ssw0rd for this example only.
        password_hash: "$argon2id$v=19$m=19456,t=2,p=1$YXV0aG90cm9uLWRvYy0wMQ$9SHjr4wGPrTaxgJJ+ELNof/S/JXH7gN6LYGAwVo4qL4"
  - name: "ECMWF API Provider"
    type: "ecmwf-api"
    uri: https://api.ecmwf.int/v1
    realm: "ecmwf"

store:
  enabled: false
  # type: mongo
  # database: tokens
  # uri: mongodb://mongodb:27017

services: []

jwt:
  exp: 3600
  iss: authotron-test
  secret: some-secret-key
  aud: authotron-test

server:
  host: "0.0.0.0"
  port: 8080