version: '3.8'

services:
  auth-o-tron:
    image: eccr.ecmwf.int/auth-o-tron/auth-o-tron:0.2.5
    container_name: auth-o-tron
    restart: unless-stopped
    # mount our existing config file in read-only mode
    volumes:
      - ./config/auth-o-tron.yml:/etc/auth-o-tron/config.yml:ro
    environment:
      - AOT_CONFIG_PATH=/etc/auth-o-tron/config.yml
    networks:
      - authnet

  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    # mount our custom nginx.conf
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-o-tron
      - api
    networks:
      - authnet

  api:
    image: kennethreitz/httpbin
    container_name: api-backend
    restart: unless-stopped
    # no ports published: only nginx can talk to it
    networks:
      - authnet

networks:
  authnet:
    driver: bridge
